services:
  freeipa:
    image: quay.io/freeipa/freeipa-server:rocky-9
    container_name: freeipa
    # You want to use `authbind` to bind to ports <1024 on rootless containers.
    ports:
      # DNS (Disabled by default, flag `--enable-dns` must be set):
      #- "53:53"
      #- "53:53/udp"
      # HTTP:
      - "80:80"
      # Kerberos:
      - "88:88"
      - "88:88/udp"
      # NTP:
      - "123:123/udp"
      # LDAP:
      - "389:389"
      # HTTPS
      - "443:443"
      # kpasswd:
      - "464:464"
      - "464:464/udp"
      # LDAPS:
      - "636:636"
    env_file:
      - ./.env.freeipa
    volumes:
      - freeipa-data:/data
    security_opt:
      - no-new-privileges:true

volumes:
  freeipa-data: